apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amang-db-production

resources:
  - namespace.yaml
  - ../../base
  - secret.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "master"
    target:
      kind: Job
      name: db-seed
