apiVersion: v1
kind: Secret
metadata:
  name: db-job-secrets
type: Opaque
stringData:
  # TODO: Replace with actual production DATABASE_URL
  DATABASE_URL: "postgresql://postgres:CHANGE_ME@db-service.amang-db-production:5432/amang_db?schema=public"
