apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  # TODO: encrypt with Sealed Secrets
  ACCESS_TOKEN_SECRET: aasfeawfawj123f3a21afnifn23r4239rj23
  REFRESH_TOKEN_SECRET: aasfeawfawj123f3a21afnifn23r4239rj23
  DATABASE_URL: postgresql://postgres:postgres@postgres-svc.amang-db-production:5432/amang_db?schema=public
  S3_ACCESS_KEY: 1dde14d97b0db5b7
  S3_SECRET_KEY: b5e03a6c794a3096dbec83fe23e09c3f
