# TODO: namespace를 ArgoCD Application에서 지정하고 여기서 제거 검토
# ref: https://github.com/manamana32321/homelab/tree/main/k8s/argocd/applications/apps/amang
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amang-web-production

resources:
  - namespace.yaml
  - configmap.yaml
  - ../../base
  - ingress.yaml
  - secret.yaml
