apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  # TODO: encrypt with Sealed Secrets
  ACCESS_TOKEN_SECRET: aasfeawfawj123f3a21afnifn23r4239rj23
  REFRESH_TOKEN_SECRET: aasfeawfawj123f3a21afnifn23r4239rj23
  DATABASE_URL: postgresql://postgres:postgres@postgres-svc.amang-db-staging:5432/amang_db?schema=public
  S3_ACCESS_KEY: 8df183d2d9add022
  S3_SECRET_KEY: da6a9a796ca3ba0147150ff0081dccc7
  SEED_DEFAULT_PASSWORD: test1234!
